/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_carlossanabria;

import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP1
 */
public class lab8p2_carlossanabria extends javax.swing.JFrame {

    /**
     * Creates new form lab8p2_carlossanabria
     */
    public lab8p2_carlossanabria() {
        initComponents();
        DefaultComboBoxModel modelo1= (DefaultComboBoxModel) CB_Categoria.getModel();
        modelo1.addElement("Default");
        modelo1.addElement("Generalista");
        modelo1.addElement("Premium");
        modelo1.addElement("Deportivo");
        CB_Categoria.setModel(modelo1);
        DefaultComboBoxModel modelo2= (DefaultComboBoxModel) CB_TipoCarro.getModel();
        modelo2.addElement("Default");
        modelo2.addElement("Sedan");
        modelo2.addElement("Familiar");
        modelo2.addElement("HatchBack");
        modelo2.addElement("FastBack");
        modelo2.addElement("SUV");
        CB_TipoCarro.setModel(modelo2);
        DefaultComboBoxModel modelo3= (DefaultComboBoxModel) CB_TipoMotor1.getModel();
        modelo3.addElement("Default");
        modelo3.addElement("Combustion");
        modelo3.addElement("Electrico");
        CB_TipoMotor1.setModel(modelo3);
        DefaultComboBoxModel modelo4= (DefaultComboBoxModel) CB_TipoHibrido.getModel();
        modelo4.addElement("Ninguno");
        modelo4.addElement("MicroHibrido");
        modelo4.addElement("Hibrido Convencional");
        modelo4.addElement("Hibrido Enchufable");
        modelo4.addElement("Hibrido Electrico");
        CB_TipoHibrido.setModel(modelo4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CRUD_AUTOS = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        CB_Marca = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TF_VIN = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        JB_AgregarAuto = new javax.swing.JButton();
        TF_Color = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TF_Precio = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JS_num_p = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CB_Categoria = new javax.swing.JComboBox<>();
        JB_Prepar_Marca = new javax.swing.JButton();
        CB_TipoCarro = new javax.swing.JComboBox<>();
        CB_TipoHibrido = new javax.swing.JComboBox<>();
        CB_TipoMotor1 = new javax.swing.JComboBox<>();
        JS_Pasajeros = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        JS_Ensamblaje = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        JT_ListarAutos = new javax.swing.JTable();
        JB_Modificar = new javax.swing.JButton();
        JB_Eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BuscarVIN = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TF_VIN1 = new javax.swing.JTextField();
        JB_VIN = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        JT_BusquedaVIN = new javax.swing.JTable();
        BuscarAtributoLibre = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        JT_BusquedaAtributo = new javax.swing.JTable();
        TF_AtriburoLibre = new javax.swing.JTextField();
        JB_AtributoLibre = new javax.swing.JButton();
        BuscarCategoria = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        JT_BusquedaCategoria = new javax.swing.JTable();
        TF_Categoria = new javax.swing.JTextField();
        JB_Categoria = new javax.swing.JButton();
        BuscarMarcas = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        JT_BusquedaMarcas = new javax.swing.JTable();
        TF_Marcas1 = new javax.swing.JTextField();
        JB_Marcas1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JB_SALIR = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        CRUD_AUTOS.setTitle("CRUD");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("Ensamblaje: ");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setText("Cantidad Maxima de Pasajeros: ");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setText("Tipo de Hibrido: ");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Categoria: ");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setText("Precios de Partida: ");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Tipo de Auto: ");

        JB_AgregarAuto.setText("Agregar");
        JB_AgregarAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregarAutoMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Numero de puertas: ");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Tipo de motor: ");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("VIN:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Marca: ");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Color: ");

        JB_Prepar_Marca.setText("Listar Marcas");
        JB_Prepar_Marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_Prepar_MarcaMouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("En segundos");

        JT_ListarAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Color", "Marca", "VIN", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(JT_ListarAutos);

        JB_Modificar.setText("Modificar Auto");
        JB_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_ModificarMouseClicked(evt);
            }
        });

        JB_Eliminar.setText("Eliminar Auto");
        JB_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_EliminarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("CRUD AUTOS: ");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout CRUD_AUTOSLayout = new javax.swing.GroupLayout(CRUD_AUTOS.getContentPane());
        CRUD_AUTOS.getContentPane().setLayout(CRUD_AUTOSLayout);
        CRUD_AUTOSLayout.setHorizontalGroup(
            CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CRUD_AUTOSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JB_Modificar)
                .addGap(120, 120, 120)
                .addComponent(JB_Eliminar)
                .addGap(327, 327, 327))
            .addGroup(CRUD_AUTOSLayout.createSequentialGroup()
                .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CRUD_AUTOSLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CRUD_AUTOSLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(32, 32, 32)
                                .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JB_AgregarAuto)
                                    .addGroup(CRUD_AUTOSLayout.createSequentialGroup()
                                        .addComponent(JS_Ensamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel28))))
                            .addGroup(CRUD_AUTOSLayout.createSequentialGroup()
                                .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CRUD_AUTOSLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JS_Pasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CRUD_AUTOSLayout.createSequentialGroup()
                                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel15))
                                        .addGap(18, 18, 18)
                                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(CRUD_AUTOSLayout.createSequentialGroup()
                                                .addComponent(CB_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)
                                                .addComponent(JB_Prepar_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(TF_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TF_VIN, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JS_num_p, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CB_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CB_TipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(CRUD_AUTOSLayout.createSequentialGroup()
                                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel26))
                                        .addGap(25, 25, 25)
                                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CB_TipoHibrido, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TF_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CB_TipoMotor1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CRUD_AUTOSLayout.createSequentialGroup()
                        .addGap(511, 511, 511)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CRUD_AUTOSLayout.setVerticalGroup(
            CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CRUD_AUTOSLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CRUD_AUTOSLayout.createSequentialGroup()
                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CB_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JB_Prepar_Marca)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TF_VIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(CB_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(CB_TipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(JS_num_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TF_Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(CB_TipoMotor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(TF_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CRUD_AUTOSLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(JS_Pasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(CB_TipoHibrido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel24)
                    .addComponent(JS_Ensamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(CRUD_AUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Modificar)
                    .addComponent(JB_Eliminar))
                .addGap(18, 18, 18)
                .addComponent(JB_AgregarAuto)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        BuscarVIN.setTitle("Buscar VIN");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Busqueda por VIN");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Buscar:");

        JB_VIN.setText("Resultados");
        JB_VIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_VINMouseClicked(evt);
            }
        });

        JT_BusquedaVIN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Color", "Marca", "VIN", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(JT_BusquedaVIN);

        javax.swing.GroupLayout BuscarVINLayout = new javax.swing.GroupLayout(BuscarVIN.getContentPane());
        BuscarVIN.getContentPane().setLayout(BuscarVINLayout);
        BuscarVINLayout.setHorizontalGroup(
            BuscarVINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscarVINLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(BuscarVINLayout.createSequentialGroup()
                .addGroup(BuscarVINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuscarVINLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(TF_VIN1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_VIN))
                    .addGroup(BuscarVINLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BuscarVINLayout.setVerticalGroup(
            BuscarVINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarVINLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(116, 116, 116)
                .addGroup(BuscarVINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BuscarVINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JB_VIN)
                        .addComponent(TF_VIN1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        BuscarAtributoLibre.setTitle("Buscar Atributo Libre");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Busqueda por Atributo");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Buscar (Menos VIN,Categoria y Marcas):");

        JT_BusquedaAtributo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Color", "Tipo", "Motor", "Capacidad de pasajero", "Numero de Puertas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(JT_BusquedaAtributo);

        JB_AtributoLibre.setText("Resultados");
        JB_AtributoLibre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AtributoLibreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BuscarAtributoLibreLayout = new javax.swing.GroupLayout(BuscarAtributoLibre.getContentPane());
        BuscarAtributoLibre.getContentPane().setLayout(BuscarAtributoLibreLayout);
        BuscarAtributoLibreLayout.setHorizontalGroup(
            BuscarAtributoLibreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarAtributoLibreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(28, 28, 28)
                .addComponent(TF_AtriburoLibre, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(JB_AtributoLibre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscarAtributoLibreLayout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(BuscarAtributoLibreLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BuscarAtributoLibreLayout.setVerticalGroup(
            BuscarAtributoLibreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarAtributoLibreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(116, 116, 116)
                .addGroup(BuscarAtributoLibreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_AtributoLibre)
                    .addComponent(TF_AtriburoLibre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        BuscarCategoria.setTitle("Buscar Categoria");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setText("Busqueda por Categoria");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Buscar:");

        JT_BusquedaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Color", "Marca", "VIN", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(JT_BusquedaCategoria);

        JB_Categoria.setText("Resultados");
        JB_Categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_CategoriaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BuscarCategoriaLayout = new javax.swing.GroupLayout(BuscarCategoria.getContentPane());
        BuscarCategoria.getContentPane().setLayout(BuscarCategoriaLayout);
        BuscarCategoriaLayout.setHorizontalGroup(
            BuscarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscarCategoriaLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(BuscarCategoriaLayout.createSequentialGroup()
                .addGroup(BuscarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuscarCategoriaLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(TF_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_Categoria))
                    .addGroup(BuscarCategoriaLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BuscarCategoriaLayout.setVerticalGroup(
            BuscarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(116, 116, 116)
                .addGroup(BuscarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BuscarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JB_Categoria)
                        .addComponent(TF_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        BuscarMarcas.setTitle("Buscar Marcas");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel23.setText("Busqueda por Marcas");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setText("Buscar:");

        JT_BusquedaMarcas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Color", "Marca", "VIN", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(JT_BusquedaMarcas);

        JB_Marcas1.setText("Resultados");
        JB_Marcas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_Marcas1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BuscarMarcasLayout = new javax.swing.GroupLayout(BuscarMarcas.getContentPane());
        BuscarMarcas.getContentPane().setLayout(BuscarMarcasLayout);
        BuscarMarcasLayout.setHorizontalGroup(
            BuscarMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscarMarcasLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(BuscarMarcasLayout.createSequentialGroup()
                .addGroup(BuscarMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuscarMarcasLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(TF_Marcas1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_Marcas1))
                    .addGroup(BuscarMarcasLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel23)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BuscarMarcasLayout.setVerticalGroup(
            BuscarMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarMarcasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(116, 116, 116)
                .addGroup(BuscarMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BuscarMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JB_Marcas1)
                        .addComponent(TF_Marcas1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("MENU PRINCIPAL BIENVENIDOS: ");

        JB_SALIR.setText("Salir del sistema");
        JB_SALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_SALIRMouseClicked(evt);
            }
        });

        jMenu1.setText("Adminstrar Autos");

        jMenuItem1.setText("CRUD Autos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Busquedad Autos");

        jMenu3.setText("Buscar por: ");

        jMenuItem2.setText("VIN");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Atributos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Categoria");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Marcas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(JB_SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(JB_SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_AgregarAutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregarAutoMouseClicked
        // TODO add your handling code here:
        Adminstrar_Autos ap = new Adminstrar_Autos("./Autos.sana");
        ap.cargarArchivo();
        for (int i = 0; i < ap.getListasAutos().size(); i++) {
             if(ap.getListasAutos().get(i).getVIN()==Integer.parseInt(TF_VIN.getText())){
                 while(ap.getListasAutos().get(i).getVIN()==Integer.parseInt(TF_VIN.getText())){
                     String t=JOptionPane.showInputDialog(CRUD_AUTOS, "El VIN que ingreso ya es usado por otro Auto porfavor ingrese uno nuevo: ");
                     TF_VIN.setText(t);
                 }
             }
        }
        
        String TCarro = "";
        Object b = CB_Categoria.getSelectedItem();
        Object bb = CB_Marca.getSelectedItem();
        Object v = CB_TipoCarro.getSelectedItem();
        Object vv = CB_TipoMotor1.getSelectedItem();
         Object vvv = CB_TipoHibrido.getSelectedItem();
        String  TMotor= "";
        String  THibri= "";
        String  TCateg= "";
        String  TMarca= "";
        TCateg+=b;
        TMarca+=bb;
        TCarro+=v;
        TMotor+=vv;
        THibri+=vvv;
        Autos a = new Autos(TCateg,Integer.parseInt(TF_VIN.getText()), TMarca, TCarro, (Integer)JS_num_p.getValue(), TF_Color.getText(),
            TMotor, Double.parseDouble(TF_Precio.getText()), THibri,(Integer)JS_Pasajeros.getValue(), (Integer)JS_Ensamblaje.getValue()
        );

        Dba db = new Dba("Auto.mdb");
        db.conectar();
        try {
            db.query.execute("INSERT INTO auto"
                    + " (categoria,VIN,marca,tipo,puertas,color,motor,precio,hibrido,"
                    + "pasajeros,tiempo)"
                    + " VALUES ('" + TCateg
                    + "', '" + TF_VIN.getText()
                    + "', '" + TMarca
                    + "', '" + TCarro
                    + "', '" + JS_num_p.getValue()
                    + "', '" + TF_Color.getText()
                    + "', '" + TMotor
                    + "', '" + Double.parseDouble(TF_Precio.getText())
                    + "', '" + THibri
                    + "', "
                    + "'" + JS_Pasajeros.getValue()
                    + "', '" + JS_Ensamblaje.getValue() + "')");
            db.commit();
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        ap.cargarArchivo();
        ap.setPersona(a);
        ap.escribirArchivo();
       DefaultTableModel modelo=(DefaultTableModel)JT_ListarAutos.getModel();
       Object[] newrow={a.getCategegoria(),a.getColor(),a.getMarca(),a.getVIN(),a.getPrecio()};
       modelo.addRow(newrow);
        JT_ListarAutos.setModel(modelo);
        TF_Precio.setText("");
        TF_Color.setText("");
        TF_VIN.setText("");
        JS_num_p.setValue(0);
        JS_Pasajeros.setValue(0);
        JS_Ensamblaje.setValue(0);
        CB_Marca.setSelectedIndex(0);
        CB_Categoria.setSelectedIndex(0);
        CB_TipoCarro.setSelectedIndex(0);
        CB_TipoMotor1.setSelectedIndex(0);
        CB_TipoHibrido.setSelectedIndex(0);
        JOptionPane.showMessageDialog(CRUD_AUTOS,
            "El auto fue guardado exsitosamente");
    }//GEN-LAST:event_JB_AgregarAutoMouseClicked

    private void JB_Prepar_MarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_Prepar_MarcaMouseClicked
        // TODO add your handling code here:
        int check=CB_Categoria.getSelectedIndex();
        DefaultComboBoxModel modelo= (DefaultComboBoxModel) CB_Marca.getModel();
        modelo.removeAllElements();
        CB_Marca.setModel(modelo);
        if(check==1){
             DefaultComboBoxModel modelo1= (DefaultComboBoxModel) CB_Marca.getModel();
             modelo1.addElement("Seat");
             modelo1.addElement("SKoda");
             CB_Marca.setModel(modelo1);
        }else if(check==2){
             DefaultComboBoxModel modelo1= (DefaultComboBoxModel) CB_Marca.getModel();
             modelo1.addElement("Audi");
             modelo1.addElement("Volkswagen");
             modelo1.addElement("Bently");
             CB_Marca.setModel(modelo1);
        }else if(check==3){
             DefaultComboBoxModel modelo1= (DefaultComboBoxModel) CB_Marca.getModel();
             modelo1.addElement("Porsche");
             modelo1.addElement("Lamborghini");
             modelo1.addElement("Bugatti");
             CB_Marca.setModel(modelo1);
        }else{
            JOptionPane.showMessageDialog(CRUD_AUTOS, "Por favor selecione un opcion que no sea Default ");
        }
    }//GEN-LAST:event_JB_Prepar_MarcaMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Adminstrar_Autos ap = new Adminstrar_Autos("./Autos.sana");
        ap.cargarArchivo();
        DefaultTableModel modelo=(DefaultTableModel)JT_ListarAutos.getModel();
                for (int i = 0; i < ap.getListasAutos().size(); i++) {
                    Object[] newrow={ap.getListasAutos().get(i).getCategegoria(),ap.getListasAutos().get(i).getColor(),ap.getListasAutos().get(i).getMarca(),ap.getListasAutos().get(i).getVIN(),ap.getListasAutos().get(i).getPrecio()};
                    modelo.addRow(newrow);
                }//fin del for
                JT_ListarAutos.setModel(modelo);
                JDCRUD();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JB_ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ModificarMouseClicked
        // TODO add your handling code here:
         Adminstrar_Autos ap = new Adminstrar_Autos("./Autos.sana");
        int p;
        p = JT_ListarAutos.getSelectedRow();

        ap.cargarArchivo();
        int help = ap.getListasAutos().get(p).getVIN();
        ap.getListasAutos().get(p).setCategegoria(JOptionPane.showInputDialog("Categoria: "));
        ap.getListasAutos().get(p).setMarca(JOptionPane.showInputDialog("Marca: "));
        ap.getListasAutos().get(p).setTipo(JOptionPane.showInputDialog("Tipo Carro: "));
        ap.getListasAutos().get(p).setNum_puertas(Integer.parseInt(JOptionPane.showInputDialog("Numero de Puertas: ")));
        ap.getListasAutos().get(p).setColor(JOptionPane.showInputDialog("Color: "));
        ap.getListasAutos().get(p).setMotor(JOptionPane.showInputDialog("Tipo de Motor: "));
        ap.getListasAutos().get(p).setPrecio(Double.parseDouble(JOptionPane.showInputDialog("Precio: ")));
        ap.getListasAutos().get(p).setTipo_h(JOptionPane.showInputDialog("Tipo de Hibrido: "));
        ap.getListasAutos().get(p).setCantidad_p(Integer.parseInt(JOptionPane.showInputDialog("Cantidad de pasajeros: ")));
        ap.getListasAutos().get(p).setTiempo(Integer.parseInt(JOptionPane.showInputDialog("Tiempo en Ensamblaje: ")));
        ap.escribirArchivo();
        Dba db = new Dba("./Auto.mdb");
        db.conectar();
        try {

            db.query.execute("update carros set categoria='" + ap.getListasAutos().get(p).getCategegoria()+ "' where VIN=" + help);
            db.query.execute("update carros set marca='" + ap.getListasAutos().get(p).getMarca()+ "' where VIN=" + help);
            db.query.execute("update carros set tipo='" + ap.getListasAutos().get(p).getTipo()+ "' where VIN=" + help);
            db.query.execute("update carros set puertas='" + ap.getListasAutos().get(p).getNum_puertas()+ "' where VIN=" + help);
            db.query.execute("update carros set color='" + ap.getListasAutos().get(p).getColor()+ "' where VIN=" + help);
            db.query.execute("update carros set motor='" + ap.getListasAutos().get(p).getMotor()+ "' where VIN=" + help);
            db.query.execute("update carros set precio='" + ap.getListasAutos().get(p).getPrecio()+ "' where VIN=" + help);
            db.query.execute("update carros set hibrido='" + ap.getListasAutos().get(p).getTipo_h()+ "' where VIN=" + help);
            db.query.execute("update carros set pasajeros='" + ap.getListasAutos().get(p).getCantidad_p()+ "' where VIN=" + help);
            db.query.execute("update carros set tiempo='" + ap.getListasAutos().get(p).getTiempo()+ "' where VIN=" + help);
            db.commit();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
       
        DefaultTableModel modelo1
                = (DefaultTableModel) JT_ListarAutos.getModel();
             modelo1.setRowCount(0);
             for (int i = 0; i < ap.getListasAutos().size(); i++) {
                   Autos a = ap.getListasAutos().get(i);
                 Object[] newrow={a.getCategegoria(),a.getColor(),a.getMarca(),a.getVIN(),a.getPrecio()};
                 modelo1.addRow(newrow);
        }
         JT_ListarAutos.setModel(modelo1);
    }//GEN-LAST:event_JB_ModificarMouseClicked

    private void JB_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EliminarMouseClicked
        // TODO add your handling code here:
        Adminstrar_Autos ar
                = new Adminstrar_Autos("./Autos.sana");
        int p;
        p = JT_ListarAutos.getSelectedRow();
        int help=ar.getListasAutos().get(p).getVIN();
        ar.cargarArchivo();
        ar.getListasAutos().remove(p);
        ar.escribirArchivo();
        Dba db = new Dba("./Auto.mdb");
        db.conectar();
        try {
            db.query.execute("delete from carros where VIN='" + help + "'");
            db.commit();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        DefaultTableModel modelo1
                = (DefaultTableModel) JT_ListarAutos.getModel();
        modelo1.removeRow(p);
        JT_ListarAutos.setModel(modelo1);
    }//GEN-LAST:event_JB_EliminarMouseClicked

    private void JB_SALIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_SALIRMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JB_SALIRMouseClicked

    private void JB_VINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_VINMouseClicked
        // TODO add your handling code here:
        Adminstrar_Autos ap = new Adminstrar_Autos("./Autos.sana");
        ap.cargarArchivo();
        int p = 0;
        DefaultTableModel modelo = (DefaultTableModel) JT_BusquedaVIN.getModel();
        modelo.setRowCount(0);
        JT_BusquedaVIN.setModel(modelo);
        for (int i = 0; i < ap.getListasAutos().size(); i++) {
            if (ap.getListasAutos().get(i).getVIN()== Integer.parseInt(TF_VIN1.getText())) {
                p = i;
                Autos c = ap.getListasAutos().get(p);
                Object[] newrow = {c.getCategegoria(),
                 c.getColor(),
                 c.getMarca(),
                 c.getVIN(),
                 c.getPrecio()};
            modelo.addRow(newrow);

            }
        }//fin de las condiciones
        JT_BusquedaVIN.setModel(modelo);
        
    }//GEN-LAST:event_JB_VINMouseClicked

    private void JB_AtributoLibreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AtributoLibreMouseClicked
        // TODO add your handling code here:
        Adminstrar_Autos ap = new Adminstrar_Autos("./Autos.sana");
        ap.cargarArchivo();
        int p = 0;
        DefaultTableModel modelo = (DefaultTableModel) JT_BusquedaAtributo.getModel();
        modelo.setRowCount(0);
        JT_BusquedaAtributo.setModel(modelo);
        for (int i = 0; i < ap.getListasAutos().size(); i++) {
            if (Integer.toString(ap.getListasAutos().get(i).getCantidad_p()).equalsIgnoreCase( TF_AtriburoLibre.getText())
                    || Integer.toString(ap.getListasAutos().get(i).getCantidad_p()).equalsIgnoreCase( TF_AtriburoLibre.getText())
                    || Double.toString(ap.getListasAutos().get(i).getCantidad_p()).equalsIgnoreCase( TF_AtriburoLibre.getText())
                    || Integer.toString(ap.getListasAutos().get(i).getCantidad_p()).equalsIgnoreCase( TF_AtriburoLibre.getText())
                   ) {
                p = i;
                Autos a = ap.getListasAutos().get(p);
                Object[] newrow = {a.getColor(),
                    a.getTipo(),
                    a.getMotor(),
                    a.getCantidad_p(),
                    a.getNum_puertas()};
                modelo.addRow(newrow);
            }
            if(ap.getListasAutos().get(i).getColor().equalsIgnoreCase(TF_AtriburoLibre.getText())
                    || ap.getListasAutos().get(i).getMotor().equalsIgnoreCase(TF_AtriburoLibre.getText())
                    || ap.getListasAutos().get(i).getTipo().equalsIgnoreCase(TF_AtriburoLibre.getText())
                    || ap.getListasAutos().get(i).getTipo_h().equalsIgnoreCase(TF_AtriburoLibre.getText())){
                 p = i;
                Autos a = ap.getListasAutos().get(p);
                Object[] newrow = {a.getColor(),
                    a.getTipo(),
                    a.getMotor(),
                    a.getCantidad_p(),
                    a.getNum_puertas()};
                modelo.addRow(newrow);
                
            }
        }//fin de las condiciones
        JT_BusquedaAtributo.setModel(modelo);
    }//GEN-LAST:event_JB_AtributoLibreMouseClicked

    private void JB_CategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_CategoriaMouseClicked
        // TODO add your handling code here:
        Adminstrar_Autos ap = new Adminstrar_Autos("./Autos.sana");
        ap.cargarArchivo();
        int p = 0;
        DefaultTableModel modelo = (DefaultTableModel) JT_BusquedaCategoria.getModel();
        modelo.setRowCount(0);
        JT_BusquedaCategoria.setModel(modelo);
        if (TF_Categoria.getText().equalsIgnoreCase("premium") || TF_Categoria.getText().equalsIgnoreCase("generalista")
                || TF_Categoria.getText().equalsIgnoreCase("deportivo")) {
            for (int i = 0; i < ap.getListasAutos().size(); i++) {
                if (ap.getListasAutos().get(i).getCategegoria().equalsIgnoreCase(TF_Categoria.getText())) {
                    p = i;
                    Autos c = ap.getListasAutos().get(p);
                    Object[] newrow = {c.getCategegoria(),
                        c.getColor(),
                        c.getMarca(),
                        c.getVIN(),
                        c.getPrecio()};
                    modelo.addRow(newrow);
                }//fin del else 
            }//fin del for                       
        } else {
            JOptionPane.showMessageDialog(BuscarCategoria, "Categoria no válido");
            TF_Categoria.setText("");
        }
        JT_BusquedaCategoria.setModel(modelo);
    }//GEN-LAST:event_JB_CategoriaMouseClicked

    private void JB_Marcas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_Marcas1MouseClicked
        // TODO add your handling code here:
        Adminstrar_Autos ap = new Adminstrar_Autos("./Autos.sana");
        ap.cargarArchivo();
        int p = 0;
       DefaultTableModel modelo1
                = (DefaultTableModel) JT_BusquedaMarcas.getModel();
        modelo1.setRowCount(0);
        JT_BusquedaMarcas.setModel(modelo1);
        if (TF_Marcas1.getText().equalsIgnoreCase("Seat") || TF_Marcas1.getText().equalsIgnoreCase("SKoda")
                || TF_Marcas1.getText().equalsIgnoreCase("Audi") || TF_Marcas1.getText().equalsIgnoreCase("Volkswagen")
                || TF_Marcas1.getText().equalsIgnoreCase("Bently")|| TF_Marcas1.getText().equalsIgnoreCase("Porsche")
                || TF_Marcas1.getText().equalsIgnoreCase("Lamborghini")|| TF_Marcas1.getText().equalsIgnoreCase("Bugatti")) {
            for (int i = 0; i < ap.getListasAutos().size(); i++) {
                if (ap.getListasAutos().get(i).getMarca().equalsIgnoreCase(TF_Marcas1.getText())) {
                    Autos a = ap.getListasAutos().get(i);
                    Object[] newrow={a.getCategegoria(),a.getColor(),a.getMarca(),a.getVIN(),a.getPrecio()};
                    modelo1.addRow(newrow);
                }//fin del else 
            }//fin del for                        

        } else {
            JOptionPane.showMessageDialog(BuscarMarcas, "Marca no válida");
            TF_Marcas1.setText("");
        }
        JT_BusquedaMarcas.setModel(modelo1);
        
    }//GEN-LAST:event_JB_Marcas1MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JDBMARCAS();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JDBVIN();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JDBATRI();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JDBCATEG();
    }//GEN-LAST:event_jMenuItem4ActionPerformed
 public void JDCRUD() {
        CRUD_AUTOS.pack();
        CRUD_AUTOS.setModal(true);
        CRUD_AUTOS.setLocationRelativeTo(this);
        CRUD_AUTOS.setVisible(true);
    }
 public void JDBMARCAS() {
        BuscarMarcas.pack();
        BuscarMarcas.setModal(true);
        BuscarMarcas.setLocationRelativeTo(this);
        BuscarMarcas.setVisible(true);
    }
 public void JDBATRI() {
        BuscarAtributoLibre.pack();
        BuscarAtributoLibre.setModal(true);
        BuscarAtributoLibre.setLocationRelativeTo(this);
        BuscarAtributoLibre.setVisible(true);
    }
 public void JDBVIN() {
        BuscarVIN.pack();
        BuscarVIN.setModal(true);
        BuscarVIN.setLocationRelativeTo(this);
        BuscarVIN.setVisible(true);
    }
  public void JDBCATEG() {
        BuscarCategoria.pack();
        BuscarCategoria.setModal(true);
        BuscarCategoria.setLocationRelativeTo(this);
        BuscarCategoria.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab8p2_carlossanabria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab8p2_carlossanabria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab8p2_carlossanabria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab8p2_carlossanabria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab8p2_carlossanabria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog BuscarAtributoLibre;
    private javax.swing.JDialog BuscarCategoria;
    private javax.swing.JDialog BuscarMarcas;
    private javax.swing.JDialog BuscarVIN;
    private javax.swing.JComboBox<String> CB_Categoria;
    private javax.swing.JComboBox<String> CB_Marca;
    private javax.swing.JComboBox<String> CB_TipoCarro;
    private javax.swing.JComboBox<String> CB_TipoHibrido;
    private javax.swing.JComboBox<String> CB_TipoMotor1;
    private javax.swing.JDialog CRUD_AUTOS;
    private javax.swing.JButton JB_AgregarAuto;
    private javax.swing.JButton JB_AtributoLibre;
    private javax.swing.JButton JB_Categoria;
    private javax.swing.JButton JB_Eliminar;
    private javax.swing.JButton JB_Marcas1;
    private javax.swing.JButton JB_Modificar;
    private javax.swing.JButton JB_Prepar_Marca;
    private javax.swing.JButton JB_SALIR;
    private javax.swing.JButton JB_VIN;
    private javax.swing.JSpinner JS_Ensamblaje;
    private javax.swing.JSpinner JS_Pasajeros;
    private javax.swing.JSpinner JS_num_p;
    private javax.swing.JTable JT_BusquedaAtributo;
    private javax.swing.JTable JT_BusquedaCategoria;
    private javax.swing.JTable JT_BusquedaMarcas;
    private javax.swing.JTable JT_BusquedaVIN;
    private javax.swing.JTable JT_ListarAutos;
    private javax.swing.JTextField TF_AtriburoLibre;
    private javax.swing.JTextField TF_Categoria;
    private javax.swing.JTextField TF_Color;
    private javax.swing.JTextField TF_Marcas1;
    private javax.swing.JTextField TF_Precio;
    private javax.swing.JTextField TF_VIN;
    private javax.swing.JTextField TF_VIN1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables
}
